version: '2.4'
services:
  ol-node:
    container_name: ol-node
    build:
      context: .
    image: ol-node:latest
    networks:
      - default
    environment:
      - BC_NETWORK=main
      - BC_TUNNEL_HTTPS=false
      - BC_MINER_WORKERS=1
      - BC_RUST_MINER=false
      - BC_GRPC_RUST_MINER_PORT=50052
      - NODE_OPTIONS=--max_old_space_size=8192
    mem_limit: 9999m
    mem_reservation: 8900m
    command: start --relay-mode --rovers --rpc --ws --ui --node --scookie "${SCOOKIE:-changeme}"
    volumes:
      - db:/bc/_data
    ports:
      - "16061:16061/tcp"
      - "16061:16061/udp"
      - "3000:3000"
    restart: always

volumes:
  db:
    name: ol-db

